sylius_grid:
    grids:
        odiseo_admin_user:
            driver:
                name: doctrine/orm
                options:
                    class: Odiseo\Bundle\AdminBundle\Entity\AdminUser
            sorting:
                email: desc
            fields:
                username:
                    type: string
                    label: odiseo.ui.username
                    sortable: ~
                email:
                    type: string
                    label: odiseo.ui.email
                    sortable: ~
                enabled:
                    type: twig
                    label: odiseo.ui.enabled
                    sortable: ~
                    options:
                        template: "@OdiseoAdmin/Grid/Field/enabled.html.twig"
            filters:
                search:
                    type: string
                    label: odiseo.ui.search
                    options:
                        fields: [email, username]
                enabled:
                    type: boolean
                    label: odiseo.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete