imports:
    - { resource: "@OdiseoAdminBundle/Resources/config/grids/main.yml" }

sylius_user:
    driver: doctrine/orm
    resources:
        admin:
            user:
                classes:
                    model: Odiseo\Bundle\AdminBundle\Entity\AdminUser
                    repository: Odiseo\Bundle\AdminBundle\Doctrine\ORM\AdminUserRepository
                    form: Odiseo\Bundle\AdminBundle\Form\Type\AdminUserType
                templates: '@OdiseoAdmin/AdminUser'

sylius_grid:
    templates:
        action:
            default: "@OdiseoAdmin/Grid/Action/default.html.twig"
            archive: "@OdiseoAdmin/Grid/Action/archive.html.twig"
            create: "@OdiseoAdmin/Grid/Action/create.html.twig"
            delete: "@OdiseoAdmin/Grid/Action/delete.html.twig"
            show: "@OdiseoAdmin/Grid/Action/show.html.twig"
            update: "@OdiseoAdmin/Grid/Action/update.html.twig"
            link: "@OdiseoAdmin/Grid/Action/link.html.twig"
        filter:
            string: "@OdiseoAdmin/Grid/Filter/string.html.twig"
            boolean: "@OdiseoAdmin/Grid/Filter/boolean.html.twig"
            date: "@OdiseoAdmin/Grid/Filter/date.html.twig"
            entity: "@OdiseoAdmin/Grid/Filter/entity.html.twig"
            exists: "@OdiseoAdmin/Grid/Filter/exists.html.twig"
            money: "@OdiseoAdmin/Grid/Filter/money.html.twig"