odiseo_admin_admin_user:
    resource: |
        alias: sylius.admin_user
        section: admin
        templates: '@OdiseoAdmin/Crud'
        except: ['show']
        redirect: index
        grid: odiseo_admin_user
        permission: true
        vars:
            all:
                templates:
                    form: "@OdiseoAdmin/AdminUser/_form.html.twig"
            index:
                icon: user
    type: sylius.resource
