odiseo_admin_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: %odiseo_backend.homepage_route%
        permanent: true

odiseo_admin_security:
    resource: @OdiseoAdminBundle/Resources/config/routing/security.yml