odiseo_admin_index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: "%odiseo_admin.homepage_route%"
        permanent: true

odiseo_admin_security:
    resource: "@OdiseoAdminBundle/Resources/config/routing/security.yml"

odiseo_admin_admin_user:
    resource: "@OdiseoAdminBundle/Resources/config/routing/admin_user.yml"