odiseo_admin_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.user_security:loginAction
        _sylius:
            template: '@OdiseoAdminBundle/Security/login.html.twig'
            permission: true

odiseo_admin_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.user_security:checkAction

odiseo_admin_logout:
    path: /logout
    methods: [GET]